### ISSUE TITLE
请问在做monkey二次开发时，是如何解决找不到类似IActivityManager这种文件的

### ISSUE THREAD

**Issue by yumao123** [zhangzhao4444/Maxim#14]
如题，网上看有两种方法：
1. linux上编译安卓源码（无尝试），如果用这种方式，源码在哪里下载，是否需要和手机的安卓版本对应？
2. 从手机上将platform.jar下载，且将里面的dex文件反编译为jar包，但是尝试过三台手机都有各种问题，请问这种方式是否也适合？
有没有其他的简单方式？

**Comment by zhangzhao4444** [comment]
你好，就是第一种方式，没什么捷径。 源码在 google 中搜android aosp。 是需要与手机版本对应的




--




在 2018-05-03 16:23:08，"yumao123" <notifications@github.com> 写道：


如题，网上看有两种方法：

linux上编译安卓源码（无尝试），如果用这种方式，源码在哪里下载，是否需要和手机的安卓版本对应？
从手机上将platform.jar下载，且将里面的dex文件反编译为jar包，但是尝试过三台手机都有各种问题，请问这种方式是否也适合？
有没有其他的简单方式？

**Comment by yumao123** [comment]
感谢回复！

在 2018-05-07 20:04:43，"zhangzhao" <notifications@github.com> 写道：

你好，就是第一种方式，没什么捷径。 源码在 google 中搜android aosp。 是需要与手机版本对应的




--




在 2018-05-03 16:23:08，"yumao123" <notifications@github.com> 写道：


如题，网上看有两种方法：

linux上编译安卓源码（无尝试），如果用这种方式，源码在哪里下载，是否需要和手机的安卓版本对应？
从手机上将platform.jar下载，且将里面的dex文件反编译为jar包，但是尝试过三台手机都有各种问题，请问这种方式是否也适合？
有没有其他的简单方式？

**Comment by yumao123** [comment]
你好；还有一点不明，如果是通过编译aosp的方式，那么每个系统都要独立开发一套monkey，但是Maxim只需要一个monkey.jar和platform.jar就可以适配这么多版本的android系统，请问是怎么实现的？
因为最近也要独立开发一个定制的monkey；

**Comment by zhangzhao4444** [comment]
建议先跑通一两个版本，了解其中差异就明白如何统一了
