### ISSUE TITLE
如何可以点击到权限框允许权限？

### ISSUE THREAD

**Issue by kanelinlong** [zhangzhao4444/Maxim#15]
[Maxim] // Rejecting start of Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller cmp=com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity } in package com.google.android.packageinstaller

如何能点到权限框？

**Comment by zhangzhao4444** [comment]
请加qq说
