### ISSUE TITLE
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@d5b7316already registered!

### ISSUE THREAD

**Issue by kanelinlong** [zhangzhao4444/Maxim#17]
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@d5b7316already registered!

这种情况怎么解决呢？

**Comment by zhangzhao4444** [comment]
见 https://testerhome.com/topics/11719 常见问题排查
accessibilityservice 被其他驱动占用 agent未注销。如使用过atx 未执行unregister。
