### ISSUE TITLE
执行monkey之后，拔掉数据线monkey也停止了

### ISSUE THREAD

**Issue by 24Kshign** [zhangzhao4444/Maxim#25]
楼主你好，想请问一下，使用楼主这种方式启动monkey只能连接数据线进行操作，一旦拔掉数据线之后monkey就停止了，试过不用楼主这种方式是不会停止的，请问这种怎么解决呢？

**Comment by zhangzhao4444** [comment]
拔usb的可以用脱机的shell启动monkey
