### ISSUE TITLE
拓展对原生monkey事件比例设置的能力

### ISSUE THREAD

**Issue by walkwall** [zhangzhao4444/Maxim#29]
1、原生Monkey支持
![image](https://user-images.githubusercontent.com/7425326/64472469-98786180-d191-11e9-9df2-1a0c90fdbb24.png)
from：https://blog.csdn.net/lemon_linaa/article/details/97777852
2、Maxim支持
![image](https://user-images.githubusercontent.com/7425326/64472473-a7f7aa80-d191-11e9-9961-c39bea1433c1.png)

期望Maxim支持：
**1、pctrotation（优先级较高）**
2、pctsyskeys
调整“系统”按键事件的百分比(这些按键通常被保留，由系统使用，如Home、Back、Start Call、End Call及音量控制键)
调整横竖屏切换事件的比例
3、pctmotion
调整滑动事件的百分比(动作事件由屏幕上某处的一个down事件、一系列的伪随机事件和一 个up事件组成)

 
感谢大佬

**Comment by zhangzhao4444** [comment]
基本都支持了
1.旋转屏幕
--pct-rotation

2. pctsyskey大部分key没意义
有意义的细分为 
--pct-appswitch  切换app
--pct-back
--pct-mute  音量
--pct-reset  重启app

3. 滑动
--pct-motion
