### ISSUE TITLE
MdfppReflectionUtils isMdfEnforced encountered an exception. Cause: java.lang.UnsatisfiedLinkError: No implementation found

### ISSUE THREAD

**Issue by HeartIsBeat** [zhangzhao4444/Maxim#30]
三星note5运行失败，系统6.0.1
uiautomator没有被占用的情况
![image](https://user-images.githubusercontent.com/20472976/67937923-6de2dc00-fc09-11e9-8197-8b81aac1c810.png)

![image](https://user-images.githubusercontent.com/20472976/67937281-45a6ad80-fc08-11e9-9c14-9493034fa58e.png)
![image](https://user-images.githubusercontent.com/20472976/67937315-52c39c80-fc08-11e9-82ae-708bbbdd584c.png)

**Comment by HeartIsBeat** [comment]
pkill -9 axt-agent
这种的有些不管用，直接打开atx，关闭uiautomator

估计得用官网这种的才可以关掉uiautomator
$ curl -X DELETE $DEVICE_URL/uiautomator

**Comment by zhangzhao4444** [comment]
accessibility被占用，kill掉占用者即可正常使用
