### ISSUE TITLE
在多个小米机型上测出不符合预期的android 运行时权限未申请的crash

### ISSUE THREAD

**Issue by YellowQC** [zhangzhao4444/Maxim#31]
在多个小米机型上测出android 运行时权限未申请的crash，但实际发生crash的位置在权限申请成功的回调中，测试录屏发现申请权限弹框未弹出。小米手机上权限申请的activity如下：
com.lbe.security.miui/com.android.packageinstaller.permission.ui.GrantPermissionsActivity

**Comment by zhangzhao4444** [comment]
1.0.2021.0530 已修改
