### ISSUE TITLE
Oppo R17(android 9.0)执行特定输入时，monkey停止运行

### ISSUE THREAD

**Issue by dashixiong1018** [zhangzhao4444/Maxim#34]
执行特定输入，monkey停止运行，adbkeyboard已安装并且能够正常使用。
![QQ图片20200107151053](https://user-images.githubusercontent.com/25193637/71875991-a8647a00-3160-11ea-96cd-bf62c8844161.png)

![QQ图片20200107151100](https://user-images.githubusercontent.com/25193637/71875968-997dc780-3160-11ea-8dc9-a2192a8110fc.png)

**Comment by zhangzhao4444** [comment]
20200108已修改
