### ISSUE TITLE
不支持安卓11吗？

### ISSUE THREAD

**Issue by MonkeyJerry** [zhangzhao4444/Maxim#37]
adb shell CLASSPATH=/sdcard/monkey.jar:/sdcard/framework.jar exec app_process /system/bin tv.panda.test.monkey.Monkey -p com.android.dazhihui --throttle 200 --imagepolling --pct-touch 40 --pct-motion 20 --pct-pinchzoom 5 --pct-nav 5 --pct-majornav 5 --pct-rotation 1 --uiautomatormix --running-minutes 120 -v -v -v -v --output-directory /sdcard/maximlog

---------------------------------log---------------------------------------------------------------------------
.....
[Maxim] // Find ADBKeybaord.
[Maxim] // Device Info: Google-Pixel 4, Android Version: 11
[Maxim] strategy : uiautomator-Mix.

Cannot resolve m0: getPermissionInfo

**Comment by zhangzhao4444** [comment]
已支持11
