### ISSUE TITLE
maxim 在Android R 上测试，无法进入被测试包里面，如果开始界面是屏幕，只会在屏幕上点击

### ISSUE THREAD

**Issue by fengfeng-hight** [zhangzhao4444/Maxim#43]
maxim 在Android R 上测试，出现无法进入被测试包里面，如果开始界面是屏幕，只会在屏幕上点击，无法进入被测试包进行点击

**Comment by zhangzhao4444** [comment]
1.0.21.0530 已修改，请再试试

**Comment by fengfeng-hight** [comment]
谢谢。

发送自 Windows 10 版邮件应用

发件人: zhangzhao
发送时间: 2021年5月30日 21:11
收件人: zhangzhao4444/Maxim
抄送: fengfeng-hight; Author
主题: Re: [zhangzhao4444/Maxim] maxim 在Android R=?UTF-8?Q?_=E4=B8=8A=E6=B5=8B=E8=AF=95=EF=BC=8C=E6=97=A0=E6=B3=95=E8=BF=9B=E5=85=A5=E8=A2=AB=E6=B5=8B=E8=AF=95=E5=8C=85=E9=87=8C=E9=9D=A2=EF=BC=8C=E5=A6=82=E6=9E=9C=E5=BC=80=E5=A7=8B=E7=95=8C=E9=9D=A2=E6=98=AF=E5=B1=8F=E5=B9=95=EF=BC=8C=E5=8F=AA=E4=BC=9A=E5=9C=A8=E5=B1=8F=E5=B9=95=E4=B8=8A=E7=82=B9=E5=87=BB?==?UTF-8?Q?_=28#43=29?=

1.0.21.0530 已修改，请再试试
