### ISSUE TITLE
maxism截图未生成

### ISSUE THREAD

**Issue by ftvbftvbq** [zhangzhao4444/Maxim#44]
已将加了配置的：max.takeScreenShot = true配置文件max.config推送到sdcard，并且在命令行执行成功，在指定的文件夹下未生成对应的单步截图。

**Comment by wangyan841331749** [comment]
请问你解决了吗，我这边也是，截图功能不能复现，有的时候可以，有的时候不可以

**Comment by ftvbftvbq** [comment]
可以了，我自己安装的东西有问题


















在 2021-01-23 20:55:08，"Wang Yan" <notifications@github.com> 写道：

请问你解决了吗，我这边也是，截图功能不能复现，有的时候可以，有的时候不可以

**Comment by zhangzhao4444** [comment]
截图应该是正常的
