### ISSUE TITLE
怎么编写max.xpath.selector让底部Tab界面从左到右遍历，并且底部Tab界面里的头部Tab界面也从左到右遍历

### ISSUE THREAD

**Issue by HK714456322** [zhangzhao4444/Maxim#47]
1、主界面有多个底部Tab，每个底部Tab界面有多个头部Tab，怎么编写max.xpath.selector让maxim底部Tab界面从左到右遍历，并且底部Tab界面里的头部Tab界面也从左到右遍历，头部Tab界面里的元素就从上到下遍历；
2、如何控制遍历的深度；
3、编写多个firstList、selectList、lastList的xpath，同个界面同时存在符合的多个元素，遍历的优先级是怎样的呢
[
  {
    "firstList": [
      {
        "xpath": "//*[contains(@text,'发现')]"
      },
      {
        "xpath": "//*[contains(@text,'X友')]"
      },
      {
        "xpath": "//*[contains(@text,'小X')]"
      },
      {
        "xpath": "//*[contains(@text,'服务')]"
      },
      {
        "xpath": "//*[contains(@text,'我')]"
      }
    ],
    "selectList": [
      {
        "xpath": "//*[@enabled='true']"
      },
      {
        "xpath": "//*[@enabled='true']//*[contains(name(),'Text')]"
      },
      {
        "xpath": "//*[@enabled='true']//*[contains(name(),'Button')]"
      },
      {
        "xpath": "//*[@enabled='true']//*[contains(name(),'Image')]"
      }
    ],
    "lastList": [
      {
        "xpath": "//*[../*[@enabled='true']]"
      },
      {
        "xpath": "//*[../../*/*[@enabled='true']]"
      },
      {
        "xpath": "//*[../../*/*[@enabled='true'] and contains(@resource-id,'tab_')]"
      },
      {
        "xpath": "//*[../../*/*[@enabled='true'] and contains(@resource-id,'iv_tab_')]"
      },
      {
        "xpath": "//*[contains(@resource-id,'HorizontalScrollView')]"
      },
      {
        "xpath": "//*[@enabled='true']//*[contains(name(),'Image')]"
      }
    ],
    "blackList": [
      {
        "xpath": "//*[contains(@resource-id,'wrapper_in_custom_title_bar')]//*[contains(@resource-id,'right_button')]"
      },
      {
        "xpath": "//*[contains(@resource-id,'share')]"
      },
      {
       "xpath": "//*[@resource-id='com.XXX.XXXX:id/fly_progress']"
      }
    ]
  }
]

**Comment by zhangzhao4444** [comment]
troy模式建议用fastbot来代替，结合强化学习更智能的遍历测试
