### ISSUE TITLE
三星6.0.1版本上执行时,monkey卡停了

### ISSUE THREAD

**Issue by pxrgod** [zhangzhao4444/Maxim#48]
在三星手机上出现了这种情况，即应用界面没有变化了，然后等了段时间，monkey也自动停止了C:\Users\panxr33970>adb shell ps | findstr tv.panda.test.monkey
shell 30226 23413 1802800 105564 hrtimer_na b6d39b1c S tv.panda.test.monkey

**Comment by zhangzhao4444** [comment]
monkey的log再提供下？
