### ISSUE TITLE
能否只在一个app中的一个游戏场景中跑

### ISSUE THREAD

**Issue by linyuser** [zhangzhao4444/Maxim#49]
通过白名单或者黑名单控制无效
另外：QQ群貌似申请后无反应

**Comment by zhangzhao4444** [comment]
一群已经满了，可以加二群。
需要限定的游戏app的场景是否有特定的activity？

**Comment by zhangzhao4444** [comment]
目前只能限定在activity内，对限定游戏中的某一个场景可能并不能满足
