### ISSUE TITLE
将activity设置为黑名单后，跑Monkey时报错，导致Monkey停止

### ISSUE THREAD

**Issue by Zekylly** [zhangzhao4444/Maxim#50]
已经将io.dcloud.feature.sdk.DCUniMPActivity添加到黑名单
跑Monkey时，出现报错信息： 
Permissions error starting schema #Intent;component=com.xxxx.xxx/io.dcloud.feature.sdk.DCUniMPActivity;end

**Comment by zhangzhao4444** [comment]
1.0.21.0530 可以再测试下？
