### ISSUE TITLE
mac 上调试Android手机，无法启动Maxim

### ISSUE THREAD

**Issue by isanfeng** [zhangzhao4444/Maxim#9]
sh-wangsf:~ wangshufeng$ adb shell CLASSPATH=/sdcard/monkey.jar:/sdcard/framework.jar exec app_process /system/bin tv.panda.test.monkey.Monkey -p com.snda.wifilocating --uiautomatormix --running-minutes 3
sh-wangsf:~ wangshufeng$

两个jar包已经push到手机的sdcard文件夹中

**Comment by zhangzhao4444** [comment]
qq 77227005 联系我下

**Comment by zhangzhao4444** [comment]
未联系，暂时先close了
